# Generated by Django 3.2.2 on 2021-05-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight_info',
            name='source',
        ),
        migrations.AddField(
            model_name='flight_info',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='flight.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight_info',
            name='destions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='flight.airport'),
        ),
    ]
